import type { JsonSchema } from '../types/schema';
import type { FormFieldDescriptor } from '../types/form';
export declare function useSchemaImport(): {
    schema: import("vue").Ref<{
        $schema?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        type?: (import("..").JsonSchemaType | import("..").JsonSchemaType[]) | undefined;
        properties?: Record<string, JsonSchema> | undefined;
        required?: string[] | undefined;
        enum?: unknown[] | undefined;
        format?: string | undefined;
        default?: unknown;
        minimum?: number | undefined;
        maximum?: number | undefined;
        minLength?: number | undefined;
        maxLength?: number | undefined;
        pattern?: string | undefined;
        items?: /*elided*/ any | undefined;
        additionalProperties?: boolean | /*elided*/ any | undefined;
    } | null, JsonSchema | {
        $schema?: string | undefined;
        title?: string | undefined;
        description?: string | undefined;
        type?: (import("..").JsonSchemaType | import("..").JsonSchemaType[]) | undefined;
        properties?: Record<string, JsonSchema> | undefined;
        required?: string[] | undefined;
        enum?: unknown[] | undefined;
        format?: string | undefined;
        default?: unknown;
        minimum?: number | undefined;
        maximum?: number | undefined;
        minLength?: number | undefined;
        maxLength?: number | undefined;
        pattern?: string | undefined;
        items?: /*elided*/ any | undefined;
        additionalProperties?: boolean | /*elided*/ any | undefined;
    } | null>;
    fields: import("vue").Ref<{
        key: string;
        path: string;
        label: string;
        description?: string | undefined;
        controlType: import("..").ControlType;
        required: boolean;
        defaultValue?: unknown;
        options?: {
            label: string;
            value: string;
        }[] | undefined;
        minimum?: number | undefined;
        maximum?: number | undefined;
        minLength?: number | undefined;
        maxLength?: number | undefined;
        children?: /*elided*/ any[] | undefined;
        itemType?: import("..").ArrayItemType | undefined;
    }[], FormFieldDescriptor[] | {
        key: string;
        path: string;
        label: string;
        description?: string | undefined;
        controlType: import("..").ControlType;
        required: boolean;
        defaultValue?: unknown;
        options?: {
            label: string;
            value: string;
        }[] | undefined;
        minimum?: number | undefined;
        maximum?: number | undefined;
        minLength?: number | undefined;
        maxLength?: number | undefined;
        children?: /*elided*/ any[] | undefined;
        itemType?: import("..").ArrayItemType | undefined;
    }[]>;
    schemaTitle: import("vue").Ref<string, string>;
    error: import("vue").Ref<string | null, string | null>;
    isLoading: import("vue").Ref<boolean, boolean>;
    importFile: (file: File) => Promise<void>;
    reset: () => void;
};
